language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - uuid-dev
            - swig
            - libldap2-dev
            - graphviz
# The sed command is a terrible hack: we can't easily install koji on Ubuntu.
# PDC does not need it, it is a dependency of kobo. However, PDC does not use
# any part of kobo that would actively use koji, se we just delete the
# offending import.
install:
    - git config --global user.name  "Travis CI"
    - git config --global user.email "pdc@product-definition-center.com"
    - export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
    - pip install -U pip wheel coveralls
    - pip install -r requirements/devel.txt
    - sed -i -E '/import (koji|rpm)/d' $(python -vc 'import kobo.rpmlib' 2>&1 | grep 'import kobo.rpmlib' | awk '{print$NF}' | sed 's/pyc$/py/')
script:
    - coverage run --source=contrib,pdc --omit='*tests.py,*/migrations/*,pdc/settings*' manage.py test --settings pdc.settings_test contrib pdc
    - make flake8
    - bash verify-migrations.sh
after_success:
    #- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy_doc; fi
    # ONLY FOR DEMO
    - make deploy_doc
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
env:
    global:
    - GH_REPO="ycheng-aa/product-definition-center"
    - secure: "wWJkzDvxs4fpFRpm6fUoTj0/akKd2vejlFE0+e5DMiFGIJkR9a27qwq8/OPCndNyrxS2ZD5LQXpscPEfeznNSZsD8Y/SHJciO4H8yuNqNpfvuJPLiE9EfshfPcWUn+Ljqdcq76aNZo+9BOuAK8dmmUeU/ValPy5hId7d1LULHuAdXyOTIuH1xD5AhfrgRy0AoimASPA1msk8EEj8XqpqKqQyxrOZ2z8sWkEzilCVyYNIxKJN9mSrt6CU0To84onUiyJpTMsYhZByN5f7lNfx2NZ2roQKYoRVXuH2EOSguF223JzXfys5BNZFUr9RKHk9DQvBQ3VhREVszmMkeB0jRl4o0ZDjJupLwMfvgBC8SljstgtlvPmOvxnDB/XzeDh4dZonPgiFBhnzzfLMfNpuVT3zKCgYAUBY0dfBDn6JM+zOcoYyOb295eFOUKNFxjsmxHimDdWJN965t/ElEAKG7hYNrTtAAcC5PgyeZAwpSXO3RfWnGroFgwnWTsgAUIrCAeSq/+AMhBwcCQIof5pReNcBJxbXsjA2j/WYKTrmWf006LBhH5IjEARlQpderKmLIyCMynb/ljqjLo6J/2Lgx0EXTx10vMqNbYOfGuN6YGADa671mhmp0uBZ1xj5ydEn6afjmGOKWAirK5AjbMbrUr99JvmpjZeQP/1zN//IKPw="